config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  
  get 'books'=>"books#index"
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  
  
  post 'books'=>'books#create'
  
  patch 'books/:id/edit' => 'books#update', as: 'update_book'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new(params[:id])
  end
  
  def create
    @book = Book.new(book_params)
   if @book.save
     redirect_to book_path (@book.id)
    flash[:notice]="Book was successfully created."
   else
     @books = Book.all
     render :index
   end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    flash[:notice]="Book was successfully destroyed."
  end
  
  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path (@book.id)
    flash[:notice]="Book was successfully updated."
   else
    render :edit
   end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f| %>
<% if @book.errors.any? %>
    <div id="error_explanation">
     <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
     <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
     </ul>
    </div>
<% end %>
<div class="field">
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
</div>

<div class="field">
    <label for="book_body">Body</label>
    <%= f.text_area :body %>
</div>

<div class="actions">
    <%= f.submit'Update Book' %>
</div>

<% end %>

<td><%= link_to "Show", book_path(@book) %></td>
  |
<td><%= link_to "Back", '/books' %></td>

app/views/books/index.html.erb
     <p id="notice"><%= notice %></p>
     <h1>Books</h1>
     <table>
         <thead>
             <tr>
                 <th>Title</th>
                 <th>Body</th>
                 <th colspan="3"></th>
             </tr>
         </thead>
         <tbody>
          <% @books.each do |book| %>
          <tr>
             <td><%= book.title %></td>
             <td><%= book.body %></td>
             <td><%= link_to "Show", book_path(book.id) %></td>
             <td><%= link_to "Edit", edit_book_path(book) %></td>
             <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
          </tr>
          <% end %>
         </tbody>
     </table>
     <h2>New book</h2>
     <%= form_with model: @book, local:true do |f| %>
     <form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value>
        <% if @book.errors.any? %>
        <div id="error_explanation">
         <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <div class="field">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        </div>
        <div class="field">
          <label for="book_body">Body</label>
          <%= f.text_area :body %>
        </div>
        <div class="actions">
          <%= f.submit'Create Book' %>
        </div>
        <% end %>
     </form>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Title:</strong>
    <td><%= @book.title %></td>
  </p>
  <p>
    <strong>Body:</strong>
    <td><%= @book.body %></td>
  </p>
  <td><%= link_to "Edit", edit_book_path(@book) %></td>
  |
  <td><%= link_to "Back", '/books' %></td>
</body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Bookers</title>
  </head>
  <body>
    <h1>
      ようこそ
      <strong>Bookers</strong>
      へ！
    </h1>
    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <p>
      <td><%= link_to "start", '/books' %></td>
    </p>
  </body>
  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>